# Generated by Django 4.2.7 on 2024-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi2corp', '0003_signin_upload_cv_upload_resume_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_resume',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='upload_resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='upload_resume'),
        ),
    ]
