# Generated by Django 4.2.7 on 2024-05-10 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi2corp', '0004_upload_resume_email_upload_resume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
